### ISSUE TITLE
Missing dataset

### ISSUE THREAD

**Issue by efakinpelu** [ou-developers/ou-generativeai-pro#1]
While this is not critical to understanding the course described here. The pdf files referenced for the population of the chroma database (or FAISS) is not included in the git repo nor is there a reference to it.

It might help if included to help with generating similar results to the content of the courseware ou-generative-ai.

Thanks

**Comment by Ritesh2107** [comment]
I have been facing the same issue but couldn't get any solution.

**Comment by johnny-brav0** [comment]
+1

**Comment by revnav** [comment]
Same here. I was checking on the OU communities and Himanshu mentioned to follow the student guide: https://community.oracle.com/ou/discussion/9452/oci-generative-ai-professional-ayi-419196-s1107455gc10?utm_source=community-search&utm_medium=organic-search&utm_term=pdf-docs

However there is nothing in the student guide that points to pdf-docs, seems like it was part of the repo and then subsequently it was removed...

Kindly fix this.

**Comment by rhimanshu909** [comment]
Added Data Directory (pdf-docs)
